# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Nightly Build

on:
  push:
    branches: [ master ]
  repository_dispatch:
    types: [ trigger-nightly ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Shallow clone

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'maven'

    - name: Test with Maven
      run: mvn -B test
      if: matrix.os != 'ubuntu-latest'

    - name: Build with Maven
      run: mvn -B package
      if: matrix.os == 'ubuntu-latest'

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        path: web-ui/target/*.zip
      if: matrix.os == 'ubuntu-latest'

